name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install wunderctl
        working-directory: testapp
        run: npm i -g @wundergraph/wunderctl

      - name: Install dependencies
        working-directory: testapp
        run: npm i

      - name: Build container
        working-directory: testapp
        run: docker build -t wundergraph .